nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/kube-version: ">= v1.31.0"
    catalog.cattle.io/rancher-version: <= v2.9.1
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0"
